<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var \Application\Model\Product[] $products
 * @var \Application\Model\Collection[] $collections
 */
?>
<div class="row">
    <div class="col-md-8">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1>Product list</h1>
                </div>
                <?php foreach ($products as $product): ?>
                    <div class="col-md-3">
                        <h3>
                            <a href="<?= $this->url('product', ['action' => 'view', 'id' => $product->getId()]) ?>">
                                <?= $this->escapeHtml($product->getTitle()) ?>
                            </a>
                        </h3>
                        <img src="<?= $this->escapeHtml($product->getPhoto()) ?>"
                             alt=" <?= $this->escapeHtml($product->getTitle()) ?>" class="img-thumbnail">
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <?= $this->partial('partial/collection_list.phtml', [
        'collections' => $collections
    ]) ?>
</div>
